

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


SET SESSION AUTHORIZATION DEFAULT;

ALTER TABLE public.candidates DISABLE TRIGGER ALL;

INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('18323ccd-490a-4d87-ba0b-7ff8428d734d', 'Leandro Mateo Prokopio', 'lmprokopio@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, PHP, Java', 'Frontend', 'Análisis de Sistemas', 'Misiones', 'Argentina', 'https://www.linkedin.com/in/leandro-mateo-prokopio-8882321ba/', 'http://www.github.com/toti05', 'basic', '- Se envía mail de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('a472886e-abe5-4e66-91b7-78e3344e65c8', 'Nicolas Josue Lohuandus', 'nlohuandus@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Phyton, Java', 'Fullstack', 'Lic. en Sistemas / Cs. de la Computación / Informática', 'Buenos Aires', 'Argentina', 'https://www.linkedin.com/in/nlohuandus/', 'http://www.github.com/Nlohuandus', 'advanced', '- Se envía mail de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('a164073a-9c91-4652-9703-d09dabbf3834', 'Jairo Marcelo Ponti', 'jairomponti@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Java', 'Fullstack', 'Tecnico electronica', 'Buenos Aires', 'Argentina', 'https://www.linkedin.com/in/jairo-marcelo-ponti-048016180/', 'http://www.github.com/JairoPonti', 'very basic', '- Se envia email de contacto.', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('ba9a89f9-d0c3-4a04-bb8b-bf6f34be5044', 'Joaquín Maximiliano Cardozo', 'cardozojoaquinm@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Java', 'Frontend', 'Ingenieria Cs. de la Computation', 'Jujuy ', 'Argentina', 'https://www.linkedin.com/in/joaquin-cardozo/', 'http://www.github.com/mlmaxi98', 'basic', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('91448b42-28b5-49c3-8864-8cabd8f1f0fa', 'Juan José  Puente Scapolatempo', 'juanpuentescapolatempo@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Java', 'Fullstack', 'Tecnico en Informatica', 'Tucuman', 'Argentina', 'https://www.linkedin.com/in/josescap/', 'http://www.github.com/josescap2', 'very basic', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('5e4dbfbd-a21d-432f-9dc0-36618b0ce58c', 'Federico Horacio Tallarico', 'fh.tallarico@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, otros, Firebase', 'Fullstack', 'Economía, Tecnicatura en Sistemas / Cs. de la Computación / Informática', 'Buenos Aires', 'Argentina', 'https://www.linkedin.com/in/federico-horacio-tallarico', 'http://www.github.com/fhtallarico', 'advanced', '- Se envia email.', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('ab947bc5-5d6b-4ab9-97ae-3caa28d58b22', 'Alfredo  Cruz', 'nzozez@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Python, Java', 'Full stack', 'Licenciatura en Sistemas', 'Jujuy', 'Argentina', 'https://www.linkedin.com/in/alfredo-cruz/', 'http://www.github.com/Alfcru', 'basic', '- Se envia email de contacto
- Primera entrevista a partir de las 15hs
- Tiene poca experiencia, lo califico como junior/semi-senior.
- Hay que agendar entrevista tecnica.', 'interviewed');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('693c9803-1d58-4a91-9ce9-351d41315c22', 'Santiago Calisaya', 'c.ttiago7@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Java, c#, otros', 'Backend', 'Videojuegos y Programación', 'Jujuy', 'Argentina', 'https://www.linkedin.com/in/scalisaya/', 'http://www.github.com/ttiago7', 'basic', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('7c29d4e4-0d6a-4ffd-8f8f-b6b8931b0140', 'Gisela Elisabeth  Capozzi', 'gisecapozzi@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Java', 'Fullstack', 'Licenciatura en Artes Audiovisuales', 'Buenos Aires', 'Argentina', 'https://www.linkedin.com/in/gisela-capozzi-3b4380181/', 'http://www.github.com/GiselaCapozzi', 'basic', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('8f99e9a0-6567-483c-92ee-252f4cb4b835', 'Adrián Dante Fabrizio Angioni Formia', 'adriandante.angioni@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, React Native, otros, Phyton', 'Frontend', 'Economía', 'Buenos Aires', 'Argentina', 'https://www.linkedin.com/in/adri%C3%A1n-a-832335ba/', 'http://www.github.com/AdrianDante', 'advanced', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('3696a463-afd7-41a8-9b83-e1af024ef8c5', 'Francisco Prato', 'prattofrancisko@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Angular, Java, React Native, Firebase, otros', 'Fullstack', 'Curso de programación', 'San Juan', 'Argentina', 'www.linkedin.com/in/franprato-dev', 'http://www.github.com/chulas21', 'intermediate', '- Se envia email de contacto
- Se encuentra en proceso con otra empresa.', 'not interested');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('94dc0287-53cd-4a40-801c-fec9d37e63a3', 'Edgar Andrés Palma Florido', 'edgar.palma9408@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, React Native, Firebase, otros', 'Frontend', 'Tecnicatura en Sistemas', 'Cordoba', 'Argentina', 'https://www.linkedin.com/in/edgar-palma9408/', 'http://www.github.com/Edgar9408	', 'basic', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('2c9dbb98-6185-4854-b154-adf35b3d6afd', 'Nicolas Aguilar', 'aguilarnicolasivan@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Phyton, React Native, Java', 'Fullstack', 'Cursos de Programación', 'Santa Fe', 'Argentina', 'https://www.linkedin.com/in/nicolasaguilar-developer/', 'http://www.github.com/nicketech', 'advanced', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('de5ee322-9fa8-4142-ae83-38e019725167', 'Lucas Agustin Mercado', 'lucasmercado101@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Phyton, Java', 'Fullstack', 'Curso de programacion', 'Buenos Aires', 'Argentina', 'https://www.linkedin.com/in/lucas-mercado-619179145/', 'http://www.github.com/Lucasmercado101', 'advanced', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('b67bcdfd-74a4-4c11-b98f-8904e85827db', 'Lucas Del Yerro', 'lucasdelye@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Java, React Native', 'Frontend', 'Curso programación', 'Buenos Aires', 'Argentina', 'https://www.linkedin.com/in/lucas-del-yerro-280590191/', 'http://www.github.com/LucasDelye', 'advanced', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('f4c43924-224e-40ae-b027-a66a50951388', 'Iván Ignacio Contreras De Luca', 'delucaivan.01@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, otros, Firebase', 'Backend', 'Curso programación', 'San Juan', 'Argentina', 'https://www.linkedin.com/in/ivan-contreras-dev', 'http://www.github.com/shlock5', 'intermediate', '- Se envia email de contacted', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('af5ba87e-b45b-44b9-a012-eb94f45ea907', 'Paolo Fernando Martin Billordo', 'paolobillordo@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, otros', 'Fullstack', 'Ingeniería Industrial, Lic. Admin. de Empresas / Contabilidad', 'Salta', 'Argentina', 'https://www.linkedin.com/in/paolo-fernando-m-billordo-380b8211b/', 'http://www.github.com/paolobillordo', 'intermediate', '- Se envía mail de contacted', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('074c78b4-bb54-4e76-aa23-4ebebaecf31f', 'Martin Pablo Mamani', 'mpm.mamani@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Java', 'Backend', 'Tecnicatura en Sistemas', 'Buenos Aires', 'Argentina', 'https://www.linkedin.com/in/martin-mamani-a6aab41a5/', 'http://www.github.com/martinMamani', 'basic', '- Se envia email de contacted', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('b1d760b8-c6d8-4d29-afd3-1f8052d636f7', 'Laura Wenli Chu', 'lizen777@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, PHP, Java', 'Fullstack', 'Tecnicatura Cs. de la Computación', 'Buenos Aires', 'Argentina', 'www.linkedin.com/in/laura-wenli-chu', 'http://www.github.com/Laura87-web', 'intermediate', '- Se envia email de contacto', 'contaced');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('9944e518-6826-48bf-93da-e43648d312d7', 'Pia Cherni', 'piaczernyk@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS', 'Fullstack', 'Arquitectura', 'Buenos Aires', 'Argentina', 'https://www.linkedin.com/in/pia-cherni/', 'http://www.github.com/PiaCz', 'advanced', '- Se envia email de contacto', 'contacted');
INSERT INTO public.candidates (id, name, email, skills, profile, education, city, country, linkedin, github, english_level, comments, status) VALUES ('0fd7052e-3ba8-4a1b-807c-34d3bece8f7d', 'Juan Segundo Sosa', 'juansesosa98@gmail.com', 'HTML, CSS, React, Redux, Node, SQL, JS, Java, React Native, Firebase, otros', 'Backend', 'Curso programación', 'Cordoba', 'Argentina', 'https://www.linkedin.com/in/juan-segundo-sosa-081a4a180', 'http://www.github.com/Juanse1998', 'basic', '- Se envia email de contacto
- Esta por firmar con otra empresa.', 'not interested');


ALTER TABLE public.candidates ENABLE TRIGGER ALL;


